name = "FlukeLazyLands"
author = "Flukesuki and more"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1f400cab074c853caf1bb1940dd82f2457b04521367df2a0b27624f2e375e15c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
