name = "FlukeLazyLands"
author = "Flukesuki and more"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "68e9003b0fe2405d24251fb7d2ff64c9026348bb0c125cac550ed3b065bb3adb"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
