name = "FlukeLazyLands"
author = "Flukesuki and more"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "656ef8466a063ce16a6d2620717916cc78e1ee4ef5eab9a30798e4468dec882e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
